columnSuffix: null
contentColumnType: string
fieldGroup: 31006d4c-2f40-498c-9a4c-69cff4fd4279 # Common
handle: image
instructions: null
name: Image
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  apiKey: ''
  defaultUploadLocationSource: 'volume:ef49b0b2-0f0c-40a6-b8e6-40b3baab9c49' # Default
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  postText: ''
  preText: ''
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:ef49b0b2-0f0c-40a6-b8e6-40b3baab9c49' # Default
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: servd\DallEFieldtype\fieldtypes\DallEField
